version: '3.6'

services:
  selenium-hub:
    image: selenium/hub:4.19
    container_name: ddev-${DDEV_SITENAME}-selenium-hub
    ports:
      - "4442-4444:4442-4444"
  chrome:
    image: selenium/node-chrome:4.19
    container_name: ddev-${DDEV_SITENAME}-chrome
    volumes:
      - /ddev/shm:/ddev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
